//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SITIOWEB.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.calculadoraasmxSoap")]
    public interface calculadoraasmxSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sumar", ReplyAction="*")]
        decimal sumar(decimal numero1, decimal numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> sumarAsync(decimal numero1, decimal numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Restar", ReplyAction="*")]
        decimal Restar(decimal numero1, decimal numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Restar", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> RestarAsync(decimal numero1, decimal numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicar", ReplyAction="*")]
        decimal Multiplicar(decimal numero1, decimal numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicar", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> MultiplicarAsync(decimal numero1, decimal numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dividir", ReplyAction="*")]
        decimal Dividir(decimal numero1, decimal numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dividir", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> DividirAsync(decimal numero1, decimal numero2);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento mensaje del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mensaje", ReplyAction="*")]
        SITIOWEB.ServiceReference1.MensajeResponse Mensaje(SITIOWEB.ServiceReference1.MensajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mensaje", ReplyAction="*")]
        System.Threading.Tasks.Task<SITIOWEB.ServiceReference1.MensajeResponse> MensajeAsync(SITIOWEB.ServiceReference1.MensajeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MensajeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Mensaje", Namespace="http://tempuri.org/", Order=0)]
        public SITIOWEB.ServiceReference1.MensajeRequestBody Body;
        
        public MensajeRequest() {
        }
        
        public MensajeRequest(SITIOWEB.ServiceReference1.MensajeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MensajeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensaje;
        
        public MensajeRequestBody() {
        }
        
        public MensajeRequestBody(string mensaje) {
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MensajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MensajeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SITIOWEB.ServiceReference1.MensajeResponseBody Body;
        
        public MensajeResponse() {
        }
        
        public MensajeResponse(SITIOWEB.ServiceReference1.MensajeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MensajeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MensajeResult;
        
        public MensajeResponseBody() {
        }
        
        public MensajeResponseBody(string MensajeResult) {
            this.MensajeResult = MensajeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface calculadoraasmxSoapChannel : SITIOWEB.ServiceReference1.calculadoraasmxSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class calculadoraasmxSoapClient : System.ServiceModel.ClientBase<SITIOWEB.ServiceReference1.calculadoraasmxSoap>, SITIOWEB.ServiceReference1.calculadoraasmxSoap {
        
        public calculadoraasmxSoapClient() {
        }
        
        public calculadoraasmxSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public calculadoraasmxSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calculadoraasmxSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calculadoraasmxSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal sumar(decimal numero1, decimal numero2) {
            return base.Channel.sumar(numero1, numero2);
        }
        
        public System.Threading.Tasks.Task<decimal> sumarAsync(decimal numero1, decimal numero2) {
            return base.Channel.sumarAsync(numero1, numero2);
        }
        
        public decimal Restar(decimal numero1, decimal numero2) {
            return base.Channel.Restar(numero1, numero2);
        }
        
        public System.Threading.Tasks.Task<decimal> RestarAsync(decimal numero1, decimal numero2) {
            return base.Channel.RestarAsync(numero1, numero2);
        }
        
        public decimal Multiplicar(decimal numero1, decimal numero2) {
            return base.Channel.Multiplicar(numero1, numero2);
        }
        
        public System.Threading.Tasks.Task<decimal> MultiplicarAsync(decimal numero1, decimal numero2) {
            return base.Channel.MultiplicarAsync(numero1, numero2);
        }
        
        public decimal Dividir(decimal numero1, decimal numero2) {
            return base.Channel.Dividir(numero1, numero2);
        }
        
        public System.Threading.Tasks.Task<decimal> DividirAsync(decimal numero1, decimal numero2) {
            return base.Channel.DividirAsync(numero1, numero2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SITIOWEB.ServiceReference1.MensajeResponse SITIOWEB.ServiceReference1.calculadoraasmxSoap.Mensaje(SITIOWEB.ServiceReference1.MensajeRequest request) {
            return base.Channel.Mensaje(request);
        }
        
        public string Mensaje(string mensaje1) {
            SITIOWEB.ServiceReference1.MensajeRequest inValue = new SITIOWEB.ServiceReference1.MensajeRequest();
            inValue.Body = new SITIOWEB.ServiceReference1.MensajeRequestBody();
            inValue.Body.mensaje = mensaje1;
            SITIOWEB.ServiceReference1.MensajeResponse retVal = ((SITIOWEB.ServiceReference1.calculadoraasmxSoap)(this)).Mensaje(inValue);
            return retVal.Body.MensajeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SITIOWEB.ServiceReference1.MensajeResponse> SITIOWEB.ServiceReference1.calculadoraasmxSoap.MensajeAsync(SITIOWEB.ServiceReference1.MensajeRequest request) {
            return base.Channel.MensajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SITIOWEB.ServiceReference1.MensajeResponse> MensajeAsync(string mensaje) {
            SITIOWEB.ServiceReference1.MensajeRequest inValue = new SITIOWEB.ServiceReference1.MensajeRequest();
            inValue.Body = new SITIOWEB.ServiceReference1.MensajeRequestBody();
            inValue.Body.mensaje = mensaje;
            return ((SITIOWEB.ServiceReference1.calculadoraasmxSoap)(this)).MensajeAsync(inValue);
        }
    }
}
